# Generated by Django 5.2.4 on 2025-08-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_teacher_bio_teacher_photo_alter_teacher_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EduBridge', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
        ),
    ]
